export default function() {
  return [
    {title: 'Jane Eyre', author: 'Charlotte Bronte', pages: 349},
    {title: 'Ender\'s Game', author: 'Orson Scott Card', pages: 300},
    {title: 'Anne of Green Gables', author: 'LM Montgomery', pages: 300},
    {title: 'Cracking the Coding Interview', author: 'Gayle Laakmann McDowell', pages: 800}
  ]
}

// KEY: application state is generated by reducer functions