export default function() {
  return [
    {title: 'Jane Eyre'},
    {title: 'Ender\'s Game'},
    {title: 'Anne of Green Gables'},
    {title: 'Cracking the Coding Interview'}
  ]
}

// KEY: application state is generated by reducer functions